name: "1. Deploy Infra for IAM cross-account"
on:
  push

jobs:
  checkout-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        run: |
          echo Checkout files...

  create-state-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Create state bucket 
        run: |
          echo Create state bucket...
