name: "1. Deploy Infra for IAM cross-account"
on:
  push:
    branches: [master]

jobs:
  checkout-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Files
        uses: actions/checkout@v2

  check-state-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Create State Bucket
        run: |
        BUCKET_EXISTS=$(aws s3api head-bucket --bucket $BUCKET_NAME 2>&1 || true)
        if [[ -z "$BUCKET_EXISTS" ]]; then 
            echo "Bucket already exist"
        else 
            echo "Creating bucket"
            suffix=`(date '+%b-%d';) | tr '[:upper:]' '[:lower:]'`
            BUCKET_NAME=domcobb747-"${suffix}" && echo $BUCKET_NAME
            echo Create state bucket...
            aws s3api create-bucket \
                --bucket $BUCKET_NAME \
                --region us-east-1  
        fi

  create-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Infra
        run: |
        terraform init -backend-config "bucket=$TF_VAR_state_bucket" -reconfigure