name: "1. Deploy Infra for IAM cross-account"
on:
  push:
    branches: [master]

jobs:
  checkout-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v2
      - name: Listing files
        uses: actions/checkout@v2
        run: |
          echo Listing files...
          ls

  create-state-bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Create state bucket 
        run: |
          echo Create state bucket...